In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('proiectCovid.csv', sep = '\t')

In [3]:
df.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"{""diabetes"", ""cerebral infarction""}","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""shortness of breath"", ""respiratory symptoms""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]","Missing[""NotAvailable""]"
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","Missing[""NotAvailable""]",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]"
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]","{""cough"", ""sputum"", ""fever""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"

In [4]:
df.columns

Index(['Age', 'Sex', 'City', 'AdministrativeDivision', 'Country',
       'GeoPosition', 'DateOfOnsetSymptoms', 'DateOfAdmissionHospital',
       'DateOfConfirmation', 'Symptoms', 'LivesInWuhan', 'LivesInWuhanComment',
       'TravelHistoryDates', 'TravelHistoryLocation', 'ReportedMarketExposure',
       'ReportedMarketExposureComment', 'ChronicDiseaseQ', 'ChronicDiseases',
       'SequenceAvailable', 'DischargedQ', 'DeathQ', 'DateOfDeath',
       'DateOfDischarge'],
      dtype='object')

In [5]:
df.describe()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
count,18917,18917,18917,18917,18917,18917,18917,18917,18917,18917,...,18917,18917,18917,18917,18917,18917,18917,18917,18917,18917
unique,209,3,707,433,136,1806,103,83,119,314,...,580,3,7,2,67,2,2,2,40,66
top,"Missing[""NotAvailable""]","Entity[""Gender"", ""Male""]","Missing[""NotAvailable""]","Entity[""AdministrativeDivision"", {""Florida"", ""...","Entity[""Country"", ""UnitedStates""]","GeoPosition[{25.6135986, -80.565963}]","Missing[""NotAvailable""]","Missing[""NotAvailable""]","DateObject[{2020, 3, 26}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]"
freq,2061,9458,11774,4075,6002,1079,14648,17056,1379,17258,...,13856,18843,18904,18160,18768,18911,18820,18768,18771,18556

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18917 entries, 0 to 18916
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            18917 non-null  object
 1   Sex                            18917 non-null  object
 2   City                           18917 non-null  object
 3   AdministrativeDivision         18917 non-null  object
 4   Country                        18917 non-null  object
 5   GeoPosition                    18917 non-null  object
 6   DateOfOnsetSymptoms            18917 non-null  object
 7   DateOfAdmissionHospital        18917 non-null  object
 8   DateOfConfirmation             18917 non-null  object
 9   Symptoms                       18917 non-null  object
 10  LivesInWuhan                   18917 non-null  object
 11  LivesInWuhanComment            18917 non-null  object
 12  TravelHistoryDates             18917 non-null  object
 13  TravelHistoryLocation          18917 non-null  object
 14  ReportedMarketExposure         18917 non-null  object
 15  ReportedMarketExposureComment  18917 non-null  object
 16  ChronicDiseaseQ                18917 non-null  bool
 17  ChronicDiseases                18917 non-null  object
 18  SequenceAvailable              18917 non-null  object
 19  DischargedQ                    18917 non-null  object
 20  DeathQ                         18917 non-null  object
 21  DateOfDeath                    18917 non-null  object
 22  DateOfDischarge                18917 non-null  object
dtypes: bool(1), object(22)
memory usage: 3.2+ MB

In [7]:
import numpy as np

In [8]:
df.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"{""diabetes"", ""cerebral infarction""}","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""shortness of breath"", ""respiratory symptoms""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]","Missing[""NotAvailable""]"
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","Missing[""NotAvailable""]",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]"
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]","{""cough"", ""sputum"", ""fever""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"

In [9]:
s1 = df['DateOfConfirmation'][0]

In [10]:
s1

'Missing["NotAvailable"]'

In [11]:
df1 = df.replace(s1, np.nan)

In [12]:
df1.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN

In [13]:
df.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"{""diabetes"", ""cerebral infarction""}","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""shortness of breath"", ""respiratory symptoms""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]","Missing[""NotAvailable""]"
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","Missing[""NotAvailable""]",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]"
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]","{""cough"", ""sputum"", ""fever""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"

In [ ]:
df2 = df.replace(s1, np.nan)

Cu ajutorul liniei de mai sus se realizeaza inlocuirea tuturor valorilor Missing["NotAvailable"] cu nan (not a number)

In [15]:
df.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"{""diabetes"", ""cerebral infarction""}","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""shortness of breath"", ""respiratory symptoms""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]","Missing[""NotAvailable""]"
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","Missing[""NotAvailable""]",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]",True,"Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]"
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]","Missing[""NotAvailable""]","{""cough"", ""sputum"", ""fever""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...","Missing[""NotAvailable""]","{""cough""}",...,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",False,"Missing[""NotAvailable""]","Missing[""NotAvailable""]","Missing[""NotAvailable""]",True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...","Missing[""NotAvailable""]"

In [16]:
df1.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN

In [17]:
df2.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,TravelHistoryLocation,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN
1,"Interval[{15, 88}]","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN

In [18]:
df2['sym'] = df2['Symptoms'].str.replace('"',' ').str.replace("{",' ').str.replace('}',' ')

In [19]:
alex = df2['sym'].str.get_dummies(sep = ' ')

In[18] si IN[19] nu ajuta la parsarea coloanei cu Simptome. In[18] face niste replace-uri astfel incat toate simptomele sa fie despartite prin virgula, sa nu se mai afle intre parantezele { } si nici in interiorul " ". Dupa replace se apeleaza get_dummies care face metoda de one hot encoding pentru simptome. Mai exact se creeaza cate o noua coloana pentru fiecare simptom aferent, iar fiecare pacient care a suferit de acel simptom va avea valoarea 1 in dreptul coloanei cu simptomul respectiv. OHE ne genereaza undeva la 90+ coloane noi.

In [20]:
alex.head()

,",","37,","38,",39,COVID-19,DegreesCelsius,"Quantity[37.,","Quantity[37.1,","Quantity[37.2,","Quantity[37.5,",...,syndrome,systemic,throat,to,toothache,viral,vomiting,walking,weakness,wheezing
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
df2['Age'] = df2['Age'].str.replace("Interval",' ').str.replace("[",'').str.replace("{",'').str.replace("}",'').str.replace("]",'')

In [22]:
df2.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge,sym
0,48,"Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN,"cough , fatigue , fever , sputum , myalg..."
1,"15, 88","Entity[""Gender"", ""Female""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN,"shortness of breath , respiratory symptoms"
2,61,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN,NaN
3,58,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN,"cough , sputum , fever"
4,66,"Entity[""Gender"", ""Male""]","Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN,cough

In [23]:
df2['Sex'] = df2['Sex'].str.replace("Entity",' ').str.replace("[",' ').str.replace("Gender",' ').str.replace('"',' ').str.replace(',',' ').str.replace("]",' ').str.replace("Female",'F').str.replace("Male",'M')

In [24]:
df2.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge,sym
0,48,F,"Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN,"cough , fatigue , fever , sputum , myalg..."
1,"15, 88",F,"Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN,"shortness of breath , respiratory symptoms"
2,61,M,"Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN,NaN
3,58,M,"Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN,"cough , sputum , fever"
4,66,M,"Entity[""City"", {""Wuhan"", ""Hubei"", ""China""}]","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN,cough

In [25]:
df2['City'] = df2['City'].str.replace("Entity",'').str.replace("[",'').str.replace("City",'').str.replace('"','').str.replace('}','').str.replace(']','').str.replace('{','').str.replace(' ','')

In [26]:
df2.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge,sym
0,48,F,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN,"cough , fatigue , fever , sputum , myalg..."
1,"15, 88",F,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN,"shortness of breath , respiratory symptoms"
2,61,M,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN,NaN
3,58,M,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN,"cough , sputum , fever"
4,66,M,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...","Entity[""Country"", ""China""]","GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN,cough

In [27]:
df2['Country'] = df2['Country'].str.replace("Entity",'').str.replace('[','').str.replace(']','').str.replace("Country",'').str.replace(',','').str.replace(' ','').str.replace('"','')

In [28]:
df2.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge,sym
0,48,F,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...",China,"GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,"DateObject[{2020, 1, 20}, ""Day"", ""Gregorian"", ...",NaN,"cough , fatigue , fever , sputum , myalg..."
1,"15, 88",F,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...",China,"GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN,"shortness of breath , respiratory symptoms"
2,61,M,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...",China,"GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,False,NaN,True,NaN,True,"DateObject[{2020, 1, 9}, ""Day"", ""Gregorian"", -5.]",NaN,NaN
3,58,M,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...",China,"GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...",NaN,"cough , sputum , fever"
4,66,M,",Wuhan,Hubei,China","Entity[""AdministrativeDivision"", {""Hubei"", ""Ch...",China,"GeoPosition[{30.625059999999998, 114.3421}]","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,False,NaN,NaN,NaN,True,"DateObject[{2020, 1, 21}, ""Day"", ""Gregorian"", ...",NaN,cough

In [29]:
df2['AdministrativeDivision'] = df2['AdministrativeDivision'].str.replace("Entity",'').str.replace('[','').str.replace(']','').str.replace('"','').str.replace('{','').str.replace('}','').str.replace("AdministrativeDivision,",'')

In [30]:
df2['GeoPosition'] = df2['GeoPosition'].str.replace("GeoPosition",'').str.replace(']','').str.replace('"','').str.replace('{','').str.replace('}','').str.replace('[','')

In [31]:
df2['DateOfDeath'] = df2['DateOfDeath'].str.replace("DateObject",'').str.replace('[','').str.replace('{','').str.replace(']','').str.replace('}','').str.replace('"','').str.replace("Day",'').str.replace("Gregorian",'').str.replace("-5",'').str.replace('.','').str.replace(' ','').str.replace(',',' ')

In [32]:
df2.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,ReportedMarketExposure,ReportedMarketExposureComment,ChronicDiseaseQ,ChronicDiseases,SequenceAvailable,DischargedQ,DeathQ,DateOfDeath,DateOfDischarge,sym
0,48,F,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,NaN,NaN,True,"{""diabetes"", ""cerebral infarction""}",NaN,NaN,True,2020 1 20,NaN,"cough , fatigue , fever , sputum , myalg..."
1,"15, 88",F,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,NaN,NaN,False,NaN,NaN,NaN,True,NaN,NaN,"shortness of breath , respiratory symptoms"
2,61,M,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,NaN,NaN,False,NaN,True,NaN,True,2020 1 9,NaN,NaN
3,58,M,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,NaN,NaN,False,NaN,NaN,NaN,True,2020 1 23,NaN,"cough , sputum , fever"
4,66,M,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,NaN,NaN,False,NaN,NaN,NaN,True,2020 1 21,NaN,cough

In [33]:
alex.columns

Index([',', '37,', '38,', '39', 'COVID-19', 'DegreesCelsius', 'Quantity[37.,',
       'Quantity[37.1,', 'Quantity[37.2,', 'Quantity[37.5,',
       ...
       'syndrome', 'systemic', 'throat', 'to', 'toothache', 'viral',
       'vomiting', 'walking', 'weakness', 'wheezing'],
      dtype='object', length=142)

Replace-urile de mai sus se fac pe diferite coloane cu scopul de a curata cat mai mult dataFrame-ul nostru.

In [34]:
df2.reset_index(drop = True, inplace = True)

In [35]:
alex.reset_index(drop = True, inplace = True)

In [36]:
final = pd.concat([df2,alex], axis = 1)

Tinand cont ca rezultatul OHE pe coloana Symptoms a fost realizat intr-un nou DF a trebuit sa concatenam DF alex cu DF deja existent astfel incat sa concatenam rezultatul OHE cu tabela de dinainte OHE.

In [37]:
final.head()

,Age,Sex,City,AdministrativeDivision,Country,GeoPosition,DateOfOnsetSymptoms,DateOfAdmissionHospital,DateOfConfirmation,Symptoms,...,syndrome,systemic,throat,to,toothache,viral,vomiting,walking,weakness,wheezing
0,48,F,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...",NaN,"{""cough"", ""fatigue"", ""fever"", ""sputum"", ""myalg...",...,0,0,0,0,0,0,0,0,0,0
1,"15, 88",F,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 10}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""shortness of breath"", ""respiratory symptoms""}",...,0,0,0,0,0,0,0,0,0,0
2,61,M,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 20}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 27}, ""Day"", ""Gregorian"",...",NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,58,M,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2020, 1, 1}, ""Day"", ""Gregorian"", -5.]",NaN,"{""cough"", ""sputum"", ""fever""}",...,0,0,0,0,0,0,0,0,0,0
4,66,M,",Wuhan,Hubei,China","Hubei, China",China,"30.625059999999998, 114.3421","DateObject[{2019, 12, 22}, ""Day"", ""Gregorian"",...","DateObject[{2019, 12, 31}, ""Day"", ""Gregorian"",...",NaN,"{""cough""}",...,0,0,0,0,0,0,0,0,0,0

In [38]:
final['DischargedQ']=final['DischargedQ'].fillna("False")

In [39]:
final['DischargedQ']

0        False
1        False
2        False
3        False
4        False
         ...
18912    False
18913    False
18914    False
18915    False
18916    False
Name: DischargedQ, Length: 18917, dtype: object

Ne apropiem tot mai mult de finalizarea parsarii fisierului nostru astfel incat linia IN[38] inlocuieste toate valorile de nan din coloana DIscharged cu False

In [40]:
final.loc[final.DischargedQ == "True", "DeathQ"] = "False"

In [41]:
final['DeathQ']

0        True
1        True
2        True
3        True
4        True
         ...
18912     NaN
18913     NaN
18914     NaN
18915     NaN
18916     NaN
Name: DeathQ, Length: 18917, dtype: object

In [42]:
final.to_csv("final.csv")

In [43]:
final['DateOfDeath'][1]

nan

In[40] pune False in coloana DeathQ aferenta pacientului a carui valore a coloanei DIscharged este True. Cu alte cuvinte, daca se stie ca valoarea coloanei DischargedQ este True inseamna ca acel pacient este externat si nu a murit.

In [44]:
Xcolumns = final[final.columns.difference(['DischargedQ','DateOfDischarge'])]

Ne pregatim pentru rularea modelului Secvential Keras. Xcolumns primeste toate datele de la DF final mai putin cele doua coloane mentionate si anume DischargedQ si DateOfDischarge

In [45]:
Xcolumns = Xcolumns.drop(['City'], axis = 1)

In [46]:
Xcolumns = Xcolumns.drop(['TravelHistoryLocation'], axis = 1)

In [47]:
Xcolumns = Xcolumns.drop(['AdministrativeDivision'], axis = 1)

In [48]:
Xcolumns = Xcolumns.drop(['Country'], axis = 1)

In [49]:
Xcolumns = Xcolumns.drop(['DateOfAdmissionHospital'], axis = 1)

In [50]:
Xcolumns = Xcolumns.drop(['DateOfConfirmation'], axis = 1)

In [51]:
Xcolumns = Xcolumns.drop(['DateOfOnsetSymptoms'], axis = 1)

Desi mi s-au parut destul de necesare datele din coloanele de mai sus, a trebuit sa le dau drop din DF care va fi trimis ca parametru de intrare modelului deoarece primeam eroarea: string can not be converted to float. Am incercat spre exemplu: Xcolumns['Country'] = Xcolumns.drop(['Country'].astype('float') dar tot degeaba, aceeasi eroare. Astfel, ca sa pot rula modelul a trebuit sa le dau drop din DF coloanelor de mai sus

In [53]:
Y = final[['DeathQ']]

Y-ul meu sau coloana a carei valori trebuie s-o aflu este DeathQ

In [54]:
Xcolumns.to_csv("Xcolumns.csv")

In [55]:
Xcolumns

,",","37,","38,",39,Age,COVID-19,ChronicDiseaseQ,ChronicDiseases,DateOfDeath,DeathQ,...,syndrome,systemic,throat,to,toothache,viral,vomiting,walking,weakness,wheezing
0,1,0,0,0,48,0,True,"{""diabetes"", ""cerebral infarction""}",2020 1 20,True,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,"15, 88",0,False,NaN,NaN,True,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,61,0,False,NaN,2020 1 9,True,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,58,0,False,NaN,2020 1 23,True,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,66,0,False,NaN,2020 1 21,True,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18912,0,0,0,0,"60, 69",0,False,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
18913,0,0,0,0,39,0,False,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
18914,0,0,0,0,"40, 45",0,False,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
18915,0,0,0,0,46,0,False,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
18916,0,0,0,0,45,0,False,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [56]:
Y['DeathQ']=Y['DeathQ'].fillna('0')

<ipython-input-56-f98d0cd9135c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y['DeathQ']=Y['DeathQ'].fillna('0')

In [57]:
Y['DeathQ'] = Y['DeathQ'].str.replace("True",'1').str.replace("False",'0')

<ipython-input-57-6b76fe746505>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y['DeathQ'] = Y['DeathQ'].str.replace("True",'1').str.replace("False",'0')

In [58]:
Y

      DeathQ
0          1
1          1
2          1
3          1
4          1
...      ...
18912      0
18913      0
18914      0
18915      0
18916      0

[18917 rows x 1 columns]

Liniile de mai sus pun 0 in locului lui False si 1 in locul lui True in coloana DeathQ, adica Y-ul modelului nostru

In [59]:
import category_encoders as cat_en

cols = Xcolumns.columns
num_cols = Xcolumns._get_numeric_data().columns
cat_cols = list(set(cols) - set(num_cols)) # gaseste coloanele ce trebuie convertite folosind OHE
   
        
onehot = cat_en.OneHotEncoder(cols= cat_cols, handle_unknown='ignore', use_cat_names=True)
df_oh = onehot.fit_transform(Xcolumns)  # datasetul final

Codul de mai sus face OHE pe toate coloanele care le considera necesare pentru convertire cu OHE

In [60]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(12, input_dim=3096, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3,activation='softmax'))
model.add(Dense(1, activation='sigmoid'))

Using TensorFlow backend.

Codul de la linia de mai sus implementeaza modelul Keras Secvential.

In [61]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [62]:
df_oh.head()

,",","37,","38,",39,Age_48,"Age_ 15, 88",Age_61,Age_58,Age_66,Age_49,...,syndrome,systemic,throat,to,toothache,viral,vomiting,walking,weakness,wheezing
0,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_oh,Y,test_size=0.33,shuffle = False)

Imparitrea pentru train si test

In [64]:
ctree=model.fit(X_train, y_train, epochs=35, batch_size=10)

Epoch 1/35
12674/12674 [==============================] - 29s 2ms/step - loss: 0.1753 - accuracy: 0.9922
Epoch 2/35
12674/12674 [==============================] - 29s 2ms/step - loss: 0.0482 - accuracy: 0.9997
Epoch 3/35
12674/12674 [==============================] - 52s 4ms/step - loss: 0.0241 - accuracy: 0.9998
Epoch 4/35
12674/12674 [==============================] - 75s 6ms/step - loss: 0.0147 - accuracy: 1.0000
Epoch 5/35
12674/12674 [==============================] - 74s 6ms/step - loss: 0.0098 - accuracy: 1.0000
Epoch 6/35
12674/12674 [==============================] - 75s 6ms/step - loss: 0.0068 - accuracy: 1.0000
Epoch 7/35
12674/12674 [==============================] - 62s 5ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 8/35
12674/12674 [==============================] - 43s 3ms/step - loss: 0.0031 - accuracy: 1.0000
Epoch 9/35
12674/12674 [==============================] - 47s 4ms/step - loss: 0.0021 - accuracy: 1.0000 1s
Epoch 10/35
12674/12674 [==============================] - 42s 3ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 11/35
12674/12674 [==============================] - 43s 3ms/step - loss: 9.1628e-04 - accuracy: 1.0000
Epoch 12/35
12674/12674 [==============================] - 49s 4ms/step - loss: 5.9994e-04 - accuracy: 1.0000
Epoch 13/35
12674/12674 [==============================] - 45s 4ms/step - loss: 3.9333e-04 - accuracy: 1.0000
Epoch 14/35
12674/12674 [==============================] - 51s 4ms/step - loss: 2.5597e-04 - accuracy: 1.0000  - ETA: 0s - loss: 2.5696e-04 - accura
Epoch 15/35
12674/12674 [==============================] - 46s 4ms/step - loss: 1.6650e-04 - accuracy: 1.0000 0s - loss: 1.6567e-04 - accuracy:  - ETA: 0s - loss: 1.6516e-04 - ac
Epoch 16/35
12674/12674 [==============================] - 40s 3ms/step - loss: 1.0903e-04 - accuracy: 1.0000
Epoch 17/35
12674/12674 [==============================] - 38s 3ms/step - loss: 7.1315e-05 - accuracy: 1.0000
Epoch 18/35
12674/12674 [==============================] - 42s 3ms/step - loss: 4.6519e-05 - accuracy: 1.0000
Epoch 19/35
12674/12674 [==============================] - 42s 3ms/step - loss: 3.0377e-05 - accuracy: 1.0000
Epoch 20/35
12674/12674 [==============================] - 42s 3ms/step - loss: 1.9796e-05 - accuracy: 1.0000
Epoch 21/35
12674/12674 [==============================] - 44s 4ms/step - loss: 1.2853e-05 - accuracy: 1.0000
Epoch 22/35
12674/12674 [==============================] - 44s 3ms/step - loss: 8.3841e-06 - accuracy: 1.0000
Epoch 23/35
12674/12674 [==============================] - 38s 3ms/step - loss: 5.4577e-06 - accuracy: 1.0000
Epoch 24/35
12674/12674 [==============================] - 40s 3ms/step - loss: 3.5498e-06 - accuracy: 1.0000
Epoch 25/35
12674/12674 [==============================] - 38s 3ms/step - loss: 2.3175e-06 - accuracy: 1.0000
Epoch 26/35
12674/12674 [==============================] - 38s 3ms/step - loss: 1.5222e-06 - accuracy: 1.0000
Epoch 27/35
12674/12674 [==============================] - 46s 4ms/step - loss: 1.0059e-06 - accuracy: 1.0000
Epoch 28/35
12674/12674 [==============================] - 48s 4ms/step - loss: 6.6917e-07 - accuracy: 1.0000
Epoch 29/35
12674/12674 [==============================] - 75s 6ms/step - loss: 4.5104e-07 - accuracy: 1.0000
Epoch 30/35
12674/12674 [==============================] - 75s 6ms/step - loss: 3.1081e-07 - accuracy: 1.0000
Epoch 31/35
12674/12674 [==============================] - 76s 6ms/step - loss: 2.1871e-07 - accuracy: 1.0000 4s - loss: 2.1750e-07 - ac - ETA:  - ETA:
Epoch 32/35
12674/12674 [==============================] - 85s 7ms/step - loss: 1.5717e-07 - accuracy: 1.0000
Epoch 33/35
12674/12674 [==============================] - 41s 3ms/step - loss: 1.1617e-07 - accuracy: 1.0000
Epoch 34/35
12674/12674 [==============================] - 49s 4ms/step - loss: 8.8398e-08 - accuracy: 1.0000 0s - loss: 8.8225e-08 - accuracy:
Epoch 35/35
12674/12674 [==============================] - 48s 4ms/step - loss: 6.9264e-08 - accuracy: 1.0000

In [65]:
_, accuracy = model.evaluate(X_train, y_train)
print('Accuracy: %.2f' % (accuracy*100))

12674/12674 [==============================] - 16s 1ms/step
Accuracy: 100.00

In [66]:
X_train.to_csv("Xtrain.csv")

In [67]:
X_test.to_csv("X_test.csv")

In [68]:
y_test.to_csv("Y_test.csv")